name: Autofix

on:
  workflow_call:
    inputs:
      command:
        required: false
        type: string
        default: pnpm run lint:fix
      build:
        required: false
        type: string
        default: pnpm run build
      build-for-lint:
        required: false
        type: boolean
        default: false
      working-directory:
        required: false
        type: string
        default: "."

jobs:
  autofix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Setup JS
        uses: so1ve/workflows/setup-js@v1
        with:
          no-frozen-lockfile: true
          working-directory: ${{ inputs.working-directory }}

      - name: Build
        run: ${{ inputs.build }}
        if: ${{ inputs.build-for-lint }}

      - name: Fix
        run: ${{ inputs.command }}
        if: ${{ inputs.command != '' }}

      - name: Commit
        uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1.3.2
        with:
          commit-message: "chore: apply autofixes"
