name: autofix.ci

on:
  push:
    branches: [main]

  pull_request: {}

jobs:
  autofix:
    if: github.repository == 'so1ve/workflows'
    uses: so1ve/workflows/.github/workflows/autofix-ci.yml@v1
    permissions:
      contents: read
